- name: my-nginx app install
  hosts: demo
  tasks:
      - name: Recreate and start container
        vars:
            docker_network_name: my-network
            app_dir: my-nginx
            nginx_config_path: "{{ ansible_user_dir + '/' + app_dir + '/configs/nginx/default.conf' }}"
            index_html_path: "{{ ansible_user_dir + '/' + app_dir + '/index.html' }}"
        community.docker.docker_container:
            name: my-nginx
            image: "nginx:stable-alpine"
            state: started
            recreate: true
            networks:
                - name: "{{ docker_network_name }}"
            ports:
                - "8081:80"
            volumes:
                - "{{ nginx_config_path }}:/etc/nginx/conf.d/default.conf"
                - "{{ index_html_path }}:/usr/share/nginx/html/index.html"
        debugger: always
