version: "3.8"
services:
    nginx:
        image: nginx:stable-alpine
        deploy:
            mode: global
        configs:
            - source: nginx_config
              target: /etc/nginx/conf.d/default.conf
        ports:
            - 8081:80
        networks:
            - myNetwork
    db:
        image: postgres:alpine
        deploy:
            placement:
                constraints:
                    - "node.labels.db==true"
        volumes:
            - "/home/vagrant/data:/var/lib/postgresql/data"
        networks:
            - myNetwork
        environment:
            - POSTGRES_DB=myDb
            - POSTGRES_USER=myUser
            - POSTGRES_PASSWORD=myPassword
networks:
    myNetwork:
        driver: overlay

configs:
    nginx_config:
        file: ./configs/nginx/default.conf
